#include <QApplication>
#include <QPushButton>
#include <QTranslator>
#include <QLocale>
#include <QAction>
#include <QMenuBar>
#include <QMenu>
#include <QStatusBar>
#include <QGraphicsView>
#include <QResizeEvent>
#include <QGLWidget>
#include <QGraphicsScene>
#include <QtOpenGL>
#include <QDialog>
#include <QObject>
#include <QMainWindow>
#include <QDockWidget>
#include <QWidget>
#include <QLabel>
#include <QList>
#include <QVector>
#include <QIcon>
#include <QPixmap>
#include <QString>
